root: true
env:
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
settings:
  import/resolver:
    - node
    - webpack
  react:
    version: detect
rules:
  # eslint
  eqeqeq: error
  sort-imports:
    - error
    - ignoreCase: true
      ignoreDeclarationSort: true

  # eslint-plugin-react
  react/prop-types: 'off'

  # @typescript-eslint/eslint-plugin
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-non-null-assertion': 'off'
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  '@typescript-eslint/no-var-requires': 'off'

  # eslint-plugin-import
  import/order:
    - error
    - alphabetize:
        caseInsensitive: true
        order: asc
      groups:
        - builtin
        - external
        - internal
        - unknown
        - parent
        - sibling
        - index
        - type
      newlines-between: always
